<?php
$languages = [
  
  ['code' => 'none', 'label' => 'ללא כתוביות', 'flag' => 'images/flags/none.gif'],
  ['code' => 'silent', 'label' => 'ללא דיאלוג', 'flag' => 'images/flags/silent.gif'],
  ['code' => 'hebrew', 'label' => 'עברית', 'flag' => 'images/flags/hebrew.gif'],
  ['code' => 'hebdub', 'label' => 'מדובב', 'flag' => 'images/flags/hebdub.gif'],
  ['code' => 'other', 'label' => 'שפה זרה', 'flag' => 'images/flags/other.gif'],
  ['code' => 'spanish', 'label' => 'Spanish', 'flag' => 'images/flags/spanish.gif'],
  ['code' => 'french', 'label' => 'French', 'flag' => 'images/flags/french.gif'],
  ['code' => 'arabic', 'label' => 'Arabic', 'flag' => 'images/flags/arabic.gif'],
  ['code' => 'portuguese', 'label' => 'Portuguese', 'flag' => 'images/flags/portuguese.gif'],
  ['code' => 'brazilian', 'label' => 'Brazilian Port.', 'flag' => 'images/flags/brazilian-portuguese.gif'],
  ['code' => 'bulgarian', 'label' => 'Bulgarian', 'flag' => 'images/flags/bulgarian.gif'],
  ['code' => 'chinese', 'label' => 'Chinese', 'flag' => 'images/flags/chinese.gif'],
  ['code' => 'croatian', 'label' => 'Croatian', 'flag' => 'images/flags/croatian.gif'],
  ['code' => 'czech', 'label' => 'Czech', 'flag' => 'images/flags/czech.gif'],
  ['code' => 'danish', 'label' => 'Danish', 'flag' => 'images/flags/danish.gif'],
  ['code' => 'dutch', 'label' => 'Dutch', 'flag' => 'images/flags/dutch.gif'],
  ['code' => 'estonian', 'label' => 'Estonian', 'flag' => 'images/flags/estonian.gif'],
  ['code' => 'finnish', 'label' => 'Finnish', 'flag' => 'images/flags/finnish.gif'],
  ['code' => 'german', 'label' => 'German', 'flag' => 'images/flags/german.gif'],
  ['code' => 'greek', 'label' => 'Greek', 'flag' => 'images/flags/greek.gif'],
  ['code' => 'hindi', 'label' => 'Hindi', 'flag' => 'images/flags/hindi.gif'],
  ['code' => 'hungarian', 'label' => 'Hungarian', 'flag' => 'images/flags/hungarian.gif'],
  ['code' => 'icelandic', 'label' => 'Icelandic', 'flag' => 'images/flags/icelandic.gif'],
  ['code' => 'indonesian', 'label' => 'Indonesian', 'flag' => 'images/flags/indonesian.gif'],
  ['code' => 'italian', 'label' => 'Italian', 'flag' => 'images/flags/italian.gif'],
  ['code' => 'japanese', 'label' => 'Japanese', 'flag' => 'images/flags/japanese.gif'],
  ['code' => 'korean', 'label' => 'Korean', 'flag' => 'images/flags/korean.gif'],
  ['code' => 'latvian', 'label' => 'Latvian', 'flag' => 'images/flags/latvian.gif'],
  ['code' => 'lithuanian', 'label' => 'Lithuanian', 'flag' => 'images/flags/lithuanian.gif'],
  ['code' => 'malay', 'label' => 'Malay', 'flag' => 'images/flags/malay.gif'],
  ['code' => 'norwegian', 'label' => 'Norwegian', 'flag' => 'images/flags/norwegian.gif'],
  ['code' => 'persian', 'label' => 'Persian', 'flag' => 'images/flags/persian.gif'],
  ['code' => 'polish', 'label' => 'Polish', 'flag' => 'images/flags/polish.gif'],
  ['code' => 'romanian', 'label' => 'Romanian', 'flag' => 'images/flags/romanian.gif'],
  ['code' => 'russian', 'label' => 'Russian', 'flag' => 'images/flags/russian.gif'],
  ['code' => 'serbian', 'label' => 'Serbian', 'flag' => 'images/flags/serbian.gif'],
  ['code' => 'slovak', 'label' => 'Slovak', 'flag' => 'images/flags/slovak.gif'],
  ['code' => 'slovenian', 'label' => 'Slovenian', 'flag' => 'images/flags/slovenian.gif'],
  ['code' => 'swedish', 'label' => 'Swedish', 'flag' => 'images/flags/swedish.gif'],
  ['code' => 'thai', 'label' => 'Thai', 'flag' => 'images/flags/thai.gif'],
  ['code' => 'turkish', 'label' => 'Turkish', 'flag' => 'images/flags/turkish.gif'],
  ['code' => 'ukrainian', 'label' => 'Ukrainian', 'flag' => 'images/flags/ukrainian.gif'],
  ['code' => 'vietnamese', 'label' => 'Vietnamese', 'flag' => 'images/flags/vietnamese.gif'],
  ['code' => 'welsh', 'label' => 'Welsh', 'flag' => 'images/flags/welsh.gif'],
];
?>
